apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output

  params:
    - name: repo-url
      type: string

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: clone
      taskRef:
        name: git-clone
      runAfter: ["cleanup"]
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: output

    - name: eslint
      taskRef:
        name: eslint
      runAfter: ["clone"]
      workspaces:
        - name: source
          workspace: output

    - name: jest-test
      taskRef:
        name: jest-test
      runAfter: ["eslint"]
      workspaces:
        - name: source
          workspace: output